apiVersion: v1
kind: Service
metadata:
  name: activescale
  namespace: ns-observability
  labels:
    app: activescale
    workload: metrics-adapter
spec:
  selector:
    app: activescale
    workload: metrics-adapter
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: envoy-grpc
      port: 9000
      targetPort: envoy-grpc
